name: villages

description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
    sdk: '>=2.18.5 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
        ## getting icons from it
    cupertino_icons: ^1.0.5
    ## provider to manage the state
    provider: ^6.0.5 
    ## sizer to make screen responsive
    responsive_sizer: ^3.1.1
    ## navbar
    curved_navigation_bar: ^1.0.3
    ## to create datetime format
    intl: ^0.18.0
    dio: ^5.1.2
    get_storage: ^2.1.1
    webview_flutter: ^4.2.1
    font_awesome_flutter: ^10.4.0
    cached_network_image: ^3.2.3
    url_launcher: ^6.1.11
    flutter_rating_bar: ^4.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.1

    
flutter:
    uses-material-design: true
    ## set assets
    assets:
        - assets/images/
    fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/Segoe UI.ttf
        - asset: assets/fonts/Segoe UI Italic.ttf
        - asset: assets/fonts/Segoe UI Bold.ttf
        - asset: assets/fonts/Segoe UI Bold Italic.ttf

